#ifndef LAB1_CONSTANTS_H
#define LAB1_CONSTANTS_H

#define RANDOM_CHAR_READ_BLOCK_SIZE 10000
#define THREADS_AMOUNT 74
#define ALLOCATE_MBYTES 276
#define OUTPUT_FILE_SIZE 47
#define IO_BLOCK_SIZE 36
#define READ_THREADS_AMOUNT 139
#define ADDRESS 0x28B070E0
//#define LOG

#endif //LAB1_CONSTANTS_H
